#ifndef RGB2LUMA_COMMON_H
#define RGB2LUMA_COMMON_H

#define CX_GUID_VECTOR 1
#define CX_VECTOR_NUM_STATES 2
#define CX_VECTOR_NUM_FUNCS 4

#define CX_VECTOR_NUM_REGS 4
#define CX_VECTOR_VL 32
#define CX_VECTOR_STATE_SIZE (CX_VECTOR_VL * CX_VECTOR_NUM_REGS)
#define CX_NUM_VEC_INSTANCES 2

#endif  // RGB2LUMA_COMMON_H
